baseurl = "https://blog.igormihalik.com"
locale = "en-us"
title = "Anything about Everything"

canonifyurls = true
paginate = 10

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[params]
  author = "Igor Mihalik"
  description = "Notes on Go, Cloud Foundry, BOSH and other software adventures."
