baseurl = "https://blog.igormihalik.com"
languageCode = "en-us"
title = "Anything about Everything"

canonifyurls = true

[markup.goldmark.renderer]
unsafe = true

[params]
  author = "Igor Mihalik" 
